### ISSUE TITLE
on_connect callback does not pass any useful arguments

### ISSUE THREAD

**Issue by Tanami** [Leont/anyevent-handle-udp#13]
please consider passing $self so that it is possible to use it as a client module.

Also, the use of the ::Handle namespace is very confusing as it implies that ::Handle::UDP is a subclass of AnyEvent::Handle, I was very surprised when it was not!

**Comment by Leont** [comment]
> please consider passing $self so that it is possible to use it as a client module.

Yeah, that seems like a logical thing to do

> Also, the use of the ::Handle namespace is very confusing as it implies that ::Handle::UDP is a subclass of AnyEvent::Handle, I was very surprised when it was not!

In a previous incarnation it was, actually, but that turns out not to work because streams and datagrams are entirely different things semantically.
